[2023-06-27T14:58:11.144+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage permission to 509
[2023-06-27T14:58:11.145+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage'
[2023-06-27T14:58:11.190+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage permission to 509
[2023-06-27T14:58:11.191+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage'
[2023-06-27T14:58:11.420+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_stage manual__2023-06-27T14:58:09.616240+00:00 [queued]>
[2023-06-27T14:58:11.435+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_stage manual__2023-06-27T14:58:09.616240+00:00 [queued]>
[2023-06-27T14:58:11.436+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T14:58:11.471+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_stage> on 2023-06-27 14:58:09.616240+00:00
[2023-06-27T14:58:11.477+0000] {standard_task_runner.py:57} INFO - Started process 7432 to run task
[2023-06-27T14:58:11.482+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'create_stage', 'manual__2023-06-27T14:58:09.616240+00:00', '--job-id', '364', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpkrz5tq3k']
[2023-06-27T14:58:11.486+0000] {standard_task_runner.py:85} INFO - Job 364: Subtask create_stage
[2023-06-27T14:58:11.556+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage permission to 509
[2023-06-27T14:58:11.557+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_stage'
[2023-06-27T14:58:11.560+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.create_stage manual__2023-06-27T14:58:09.616240+00:00 [running]> on host eb22b15bae36
[2023-06-27T14:58:11.847+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='create_stage' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T14:58:09.616240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T14:58:09.616240+00:00'
[2023-06-27T14:58:11.857+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-27T14:58:11.858+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt run-operation create_stage --args \'{                            "stage_name": "uni_kishore_pipeline",                             "stage_url": "s3://uni-kishore-pipeline",                             "dry_run": false}\'']
[2023-06-27T14:58:11.876+0000] {subprocess.py:86} INFO - Output:
[2023-06-27T14:58:15.722+0000] {subprocess.py:93} INFO - [0m14:58:15  Running with dbt=1.5.1
[2023-06-27T14:58:19.790+0000] {subprocess.py:93} INFO - [0m14:58:19  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-27T14:58:19.791+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-06-27T14:58:19.793+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day_lu
[2023-06-27T14:58:19.843+0000] {subprocess.py:93} INFO - [0m14:58:19  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 456 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-27T14:58:21.846+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-27T14:58:21.876+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=create_stage, execution_date=20230627T145809, start_date=20230627T145811, end_date=20230627T145821
[2023-06-27T14:58:21.931+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-27T14:58:21.964+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
