[2023-06-29T11:10:15.775+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once permission to 509
[2023-06-29T11:10:15.776+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once'
[2023-06-29T11:10:15.839+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once permission to 509
[2023-06-29T11:10:15.841+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once'
[2023-06-29T11:10:16.272+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.load_seed_todl_once manual__2023-06-29T11:10:12.505155+00:00 [queued]>
[2023-06-29T11:10:16.302+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.load_seed_todl_once manual__2023-06-29T11:10:12.505155+00:00 [queued]>
[2023-06-29T11:10:16.303+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-29T11:10:16.340+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_seed_todl_once> on 2023-06-29 11:10:12.505155+00:00
[2023-06-29T11:10:16.351+0000] {standard_task_runner.py:57} INFO - Started process 6084 to run task
[2023-06-29T11:10:16.360+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'load_seed_todl_once', 'manual__2023-06-29T11:10:12.505155+00:00', '--job-id', '707', '--raw', '--subdir', 'DAGS_FOLDER/test_setup.py', '--cfg-path', '/tmp/tmpuwmkk79g']
[2023-06-29T11:10:16.365+0000] {standard_task_runner.py:85} INFO - Job 707: Subtask load_seed_todl_once
[2023-06-29T11:10:16.462+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once permission to 509
[2023-06-29T11:10:16.463+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=load_seed_todl_once'
[2023-06-29T11:10:16.467+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.load_seed_todl_once manual__2023-06-29T11:10:12.505155+00:00 [running]> on host 4f3859432e6c
[2023-06-29T11:10:16.759+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='load_seed_todl_once' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T11:10:12.505155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T11:10:12.505155+00:00'
[2023-06-29T11:10:16.764+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-29T11:10:16.767+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2023-06-29T11:10:16.789+0000] {subprocess.py:86} INFO - Output:
[2023-06-29T11:10:24.321+0000] {subprocess.py:93} INFO - [0m11:10:24  Running with dbt=1.4.6
[2023-06-29T11:10:27.627+0000] {subprocess.py:93} INFO - [0m11:10:27  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-29T11:10:27.628+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-06-29T11:10:27.629+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day_lu
[2023-06-29T11:10:27.689+0000] {subprocess.py:93} INFO - [0m11:10:27  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 442 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics
[2023-06-29T11:10:27.697+0000] {subprocess.py:93} INFO - [0m11:10:27
[2023-06-29T11:10:29.922+0000] {subprocess.py:93} INFO - [0m11:10:29  Concurrency: 200 threads (target='dev')
[2023-06-29T11:10:29.924+0000] {subprocess.py:93} INFO - [0m11:10:29
[2023-06-29T11:10:29.996+0000] {subprocess.py:93} INFO - [0m11:10:29  1 of 1 START seed file ***.time_of_day_lu .................................. [RUN]
[2023-06-29T11:10:32.541+0000] {subprocess.py:93} INFO - [0m11:10:32  1 of 1 OK loaded seed file ***.time_of_day_lu .............................. [[32mINSERT 24[0m in 2.54s]
[2023-06-29T11:10:32.663+0000] {subprocess.py:93} INFO - [0m11:10:32
[2023-06-29T11:10:32.664+0000] {subprocess.py:93} INFO - [0m11:10:32  Finished running 1 seed in 0 hours 0 minutes and 4.96 seconds (4.96s).
[2023-06-29T11:10:32.706+0000] {subprocess.py:93} INFO - [0m11:10:32
[2023-06-29T11:10:32.707+0000] {subprocess.py:93} INFO - [0m11:10:32  [32mCompleted successfully[0m
[2023-06-29T11:10:32.709+0000] {subprocess.py:93} INFO - [0m11:10:32
[2023-06-29T11:10:32.710+0000] {subprocess.py:93} INFO - [0m11:10:32  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2023-06-29T11:10:33.489+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-29T11:10:33.528+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=load_seed_todl_once, execution_date=20230629T111012, start_date=20230629T111016, end_date=20230629T111033
[2023-06-29T11:10:33.566+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-29T11:10:33.596+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
