[2023-06-29T10:14:59.973+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format permission to 509
[2023-06-29T10:14:59.975+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format'
[2023-06-29T10:15:00.019+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format permission to 509
[2023-06-29T10:15:00.020+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format'
[2023-06-29T10:15:00.068+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_file_format manual__2023-06-29T10:14:56.471038+00:00 [queued]>
[2023-06-29T10:15:00.080+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_file_format manual__2023-06-29T10:14:56.471038+00:00 [queued]>
[2023-06-29T10:15:00.080+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-29T10:15:00.101+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file_format> on 2023-06-29 10:14:56.471038+00:00
[2023-06-29T10:15:00.107+0000] {standard_task_runner.py:57} INFO - Started process 73 to run task
[2023-06-29T10:15:00.111+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'create_file_format', 'manual__2023-06-29T10:14:56.471038+00:00', '--job-id', '646', '--raw', '--subdir', 'DAGS_FOLDER/test_setup.py', '--cfg-path', '/tmp/tmp5d1ft_vc']
[2023-06-29T10:15:00.113+0000] {standard_task_runner.py:85} INFO - Job 646: Subtask create_file_format
[2023-06-29T10:15:00.185+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format permission to 509
[2023-06-29T10:15:00.186+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T10:14:56.471038+00:00/task_id=create_file_format'
[2023-06-29T10:15:00.190+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.create_file_format manual__2023-06-29T10:14:56.471038+00:00 [running]> on host 4f3859432e6c
[2023-06-29T10:15:00.417+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='create_file_format' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T10:14:56.471038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T10:14:56.471038+00:00'
[2023-06-29T10:15:00.421+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-29T10:15:00.422+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt run-operation create_file_format --args \'{                            "file_format_name": "ff_json_logs",                             "file_format_type": "JSON",                             "strip_outer_array": true,                             "dry_run": false}\'']
[2023-06-29T10:15:00.439+0000] {subprocess.py:86} INFO - Output:
[2023-06-29T10:15:06.771+0000] {subprocess.py:93} INFO - [0m10:15:06  Running with dbt=1.4.6
[2023-06-29T10:15:13.034+0000] {subprocess.py:93} INFO - [0m10:15:13  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-29T10:15:13.035+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-06-29T10:15:13.035+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day_lu
[2023-06-29T10:15:15.033+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-29T10:15:15.079+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=create_file_format, execution_date=20230629T101456, start_date=20230629T101500, end_date=20230629T101515
[2023-06-29T10:15:15.138+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-29T10:15:15.202+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
