[2023-06-26T12:11:34.480+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format permission to 509
[2023-06-26T12:11:34.482+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format'
[2023-06-26T12:11:34.527+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format permission to 509
[2023-06-26T12:11:34.529+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format'
[2023-06-26T12:11:34.572+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5.create_file_format manual__2023-06-26T12:11:32.482465+00:00 [queued]>
[2023-06-26T12:11:34.587+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5.create_file_format manual__2023-06-26T12:11:32.482465+00:00 [queued]>
[2023-06-26T12:11:34.588+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-26T12:11:34.619+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file_format> on 2023-06-26 12:11:32.482465+00:00
[2023-06-26T12:11:34.630+0000] {standard_task_runner.py:57} INFO - Started process 1325 to run task
[2023-06-26T12:11:34.637+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5', 'create_file_format', 'manual__2023-06-26T12:11:32.482465+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmppbeq2gy6']
[2023-06-26T12:11:34.641+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask create_file_format
[2023-06-26T12:11:34.724+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format permission to 509
[2023-06-26T12:11:34.726+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-26T12:11:32.482465+00:00/task_id=create_file_format'
[2023-06-26T12:11:34.729+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5.create_file_format manual__2023-06-26T12:11:32.482465+00:00 [running]> on host 84990cf1ddee
[2023-06-26T12:11:34.909+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5' AIRFLOW_CTX_TASK_ID='create_file_format' AIRFLOW_CTX_EXECUTION_DATE='2023-06-26T12:11:32.482465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-26T12:11:32.482465+00:00'
[2023-06-26T12:11:34.912+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-26T12:11:34.914+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt &&             dbt run-operation create_file_format --args \'{                "file_format_name": "ff_json_logs",                 "file_format_type": "JSON",                 "strip_outer_array": true,                 "dry_run": false}\'']
[2023-06-26T12:11:34.930+0000] {subprocess.py:86} INFO - Output:
[2023-06-26T12:11:39.709+0000] {subprocess.py:93} INFO - [0m12:11:39  Running with dbt=1.5.1
[2023-06-26T12:11:48.863+0000] {subprocess.py:93} INFO - [0m12:11:48  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-26T12:11:48.864+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2023-06-26T12:11:48.865+0000] {subprocess.py:93} INFO - - models.badge_5.create_stage
[2023-06-26T12:11:48.865+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day
[2023-06-26T12:11:48.933+0000] {subprocess.py:93} INFO - [0m12:11:48  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 455 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-26T12:11:51.067+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-26T12:11:51.111+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5, task_id=create_file_format, execution_date=20230626T121132, start_date=20230626T121134, end_date=20230626T121151
[2023-06-26T12:11:51.160+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-26T12:11:51.205+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
