[2023-06-27T14:48:37.855+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage permission to 509
[2023-06-27T14:48:37.857+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage'
[2023-06-27T14:48:37.895+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage permission to 509
[2023-06-27T14:48:37.896+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage'
[2023-06-27T14:48:38.087+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_stage manual__2023-06-27T14:48:36.176370+00:00 [queued]>
[2023-06-27T14:48:38.098+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_stage manual__2023-06-27T14:48:36.176370+00:00 [queued]>
[2023-06-27T14:48:38.099+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T14:48:38.117+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_stage> on 2023-06-27 14:48:36.176370+00:00
[2023-06-27T14:48:38.123+0000] {standard_task_runner.py:57} INFO - Started process 2911 to run task
[2023-06-27T14:48:38.127+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'create_stage', 'manual__2023-06-27T14:48:36.176370+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdafed8kg']
[2023-06-27T14:48:38.130+0000] {standard_task_runner.py:85} INFO - Job 310: Subtask create_stage
[2023-06-27T14:48:38.185+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage permission to 509
[2023-06-27T14:48:38.186+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:48:36.176370+00:00/task_id=create_stage'
[2023-06-27T14:48:38.189+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.create_stage manual__2023-06-27T14:48:36.176370+00:00 [running]> on host eb22b15bae36
[2023-06-27T14:48:38.341+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='create_stage' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T14:48:36.176370+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T14:48:36.176370+00:00'
[2023-06-27T14:48:38.344+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-27T14:48:38.346+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt run-operation create_stage --args \'{                            "stage_name": "uni_kishore_pipeline",                             "stage_url": "s3://uni-kishore-pipeline",                             "dry_run": false}\'']
[2023-06-27T14:48:38.359+0000] {subprocess.py:86} INFO - Output:
[2023-06-27T14:48:42.027+0000] {subprocess.py:93} INFO - [0m14:48:42  Running with dbt=1.5.1
[2023-06-27T14:48:46.470+0000] {subprocess.py:93} INFO - [0m14:48:46  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-27T14:48:46.471+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-06-27T14:48:46.473+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day_lu
[2023-06-27T14:48:46.536+0000] {subprocess.py:93} INFO - [0m14:48:46  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 456 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-27T14:48:48.032+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-27T14:48:48.066+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=create_stage, execution_date=20230627T144836, start_date=20230627T144838, end_date=20230627T144848
[2023-06-27T14:48:48.137+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-27T14:48:48.172+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
