[2023-06-29T11:10:16.220+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag permission to 509
[2023-06-29T11:10:16.223+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag'
[2023-06-29T11:10:16.287+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag permission to 509
[2023-06-29T11:10:16.289+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag'
[2023-06-29T11:10:16.960+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.unpause_dag manual__2023-06-29T11:10:12.505155+00:00 [queued]>
[2023-06-29T11:10:16.980+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.unpause_dag manual__2023-06-29T11:10:12.505155+00:00 [queued]>
[2023-06-29T11:10:16.981+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-29T11:10:17.012+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): unpause_dag> on 2023-06-29 11:10:12.505155+00:00
[2023-06-29T11:10:17.021+0000] {standard_task_runner.py:57} INFO - Started process 6087 to run task
[2023-06-29T11:10:17.029+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'unpause_dag', 'manual__2023-06-29T11:10:12.505155+00:00', '--job-id', '709', '--raw', '--subdir', 'DAGS_FOLDER/test_setup.py', '--cfg-path', '/tmp/tmpm9ukvd0i']
[2023-06-29T11:10:17.033+0000] {standard_task_runner.py:85} INFO - Job 709: Subtask unpause_dag
[2023-06-29T11:10:17.130+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag permission to 509
[2023-06-29T11:10:17.131+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-29T11:10:12.505155+00:00/task_id=unpause_dag'
[2023-06-29T11:10:17.136+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.unpause_dag manual__2023-06-29T11:10:12.505155+00:00 [running]> on host 4f3859432e6c
[2023-06-29T11:10:17.324+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='unpause_dag' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T11:10:12.505155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T11:10:12.505155+00:00'
[2023-06-29T11:10:17.328+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-29T11:10:17.330+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '*** dags unpause 2_Test_Badge_5_Loop']
[2023-06-29T11:10:17.345+0000] {subprocess.py:86} INFO - Output:
[2023-06-29T11:10:22.047+0000] {subprocess.py:93} INFO - Dag: 2_Test_Badge_5_Loop, paused: False
[2023-06-29T11:10:22.392+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-29T11:10:22.439+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=unpause_dag, execution_date=20230629T111012, start_date=20230629T111016, end_date=20230629T111022
[2023-06-29T11:10:22.486+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-29T11:10:22.517+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
